name: BuildingWorks
favicon: null
layout_spectrum: 0.14136681100353599
typography_spectrum: 0.6815847263205796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9188843558076769
  lightness: 0.6710249683819711
  saturation: 0.7525493213906884
  rhythmicContrast: 0.6289674255531281
purpose: []
